"""
SQLAlchemy models for the two core tables described in docs/system-design.md
section 2 (Storage choices).

TODO(Phase 0): MatchupStat's (champ_a, champ_b) columns assume the role-scoping
decision is resolved first -- if matchups are role-scoped, this table needs a
`role` column and the uniqueness constraint changes accordingly.
"""
from sqlalchemy import Column, Integer, String, Float, UniqueConstraint
from sqlalchemy.orm import declarative_base

Base = declarative_base()


class MatchupStat(Base):
    """Aggregated win-rate data from the match-data pipeline (docs/build-plan.md Phase 1)."""
    __tablename__ = "matchup_stats"

    id = Column(Integer, primary_key=True)
    champ_a = Column(String, nullable=False)
    champ_b = Column(String, nullable=False)
    rank_bracket = Column(String, nullable=False)
    phase = Column(String, nullable=False)  # early | mid | late
    win_rate = Column(Float, nullable=False)
    sample_size = Column(Integer, nullable=False)
    patch = Column(String, nullable=False)

    __table_args__ = (
        UniqueConstraint("champ_a", "champ_b", "rank_bracket", "phase", "patch"),
    )


class Advice(Base):
    """Precomputed advice text, generated by the offline batch job (Phase 3).

    fact_source_id ties each blurb back to the MatchupStat row it was generated
    from -- the fact-grounding requirement from docs/system-design.md's
    Testing & Evaluation section.
    """
    __tablename__ = "advice"

    id = Column(Integer, primary_key=True)
    champ_a = Column(String, nullable=False)
    champ_b = Column(String, nullable=False)
    rank_bracket = Column(String, nullable=False)
    phase = Column(String, nullable=False)
    text = Column(String, nullable=False)
    fact_source_id = Column(Integer, nullable=True)  # FK to MatchupStat.id
    patch = Column(String, nullable=False)
    is_abstention = Column(Integer, default=0)  # thin-data case, see architecture-evaluation.md

    __table_args__ = (
        UniqueConstraint("champ_a", "champ_b", "rank_bracket", "phase", "patch"),
    )
